### ISSUE TITLE
Unable to install in release mode

### ISSUE THREAD

**Issue by wbrickner** [BrainiumLLC/cargo-mobile#16]
Running `cargo android run --release` works perfectly, except that it produces and unsigned `.apk` which fails to install on my device.

```
adb: failed to install /Users/wbrickner/Documents/Projects/rust-powerpilot-relay/gen/android/power-pilot-relay/app/build/outputs/apk/arm64/release/app-arm64-release-unsigned.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed collecting certificates for /data/app/vmdl525558878.tmp/base.apk: Package /data/app/vmdl525558878.tmp/base.apk has no certificates at entry AndroidManifest.xml]
error: Failed to install APK
    Command "adb -s 614045f1 install /Users/wbrickner/Documents/Projects/rust-powerpilot-relay/gen/android/power-pilot-relay/app/build/outputs/apk/arm64/release/app-arm64-release-unsigned.apk" didn't complete successfully, exiting with code 1.
```

I'm new to native mobile dev, how would I configure APK signing automatically through `cargo-mobile`? 
Or should I just do it with some external system?

Thank you.

**Comment by Zeerooth** [comment]
AFAIK there are no tools in `cargo-mobile` yet to support `.apk` signing automatically so I guess you have to that manually, probably via Android Studio or by using [signing plugin provided by gradle](https://docs.gradle.org/5.2.1/userguide/signing_plugin.html)

It would be a nice feature though to be able to define your credentials/path to gpg keys in `mobile.toml` and then have `cargo-mobile` sign apk automatically (maybe there is also a way to integrate it with iOS?)

**Comment by wbrickner** [comment]
Thank you, I will try to submit a PR addressing this next week.
