### ISSUE TITLE
Failed to check Rust version on macOS when cargo mobile init

### ISSUE THREAD

**Issue by wusyong** [BrainiumLLC/cargo-mobile#22]
When I run `cargo mobile init`, It outputs the following error in the end:
```
error: Failed to check Rust version
    Failed to check rustc version: "rustc --version" output failed to match regex: "rustc 1.49.0\n"
```

The output if I run `rustc --version` is `rustc 1.49.0`. If any more info is needed, I would try my best to provide it.

Edit: I tested it on m1. Perhaps it's related to #7?

**Comment by wusyong** [comment]
Sorry, it turns out I installed it through homebrew. Use the official link works as intended.

**Comment by francesca64** [comment]
Thanks for reporting this! I'm glad you found a resolution, and I've also improved version parsing so this won't be a problem anymore: 3ad4480642de7aab78d9ed9fe5cc22558cd2f63b
