### ISSUE TITLE
APK only supports arm64-v8a

### ISSUE THREAD

**Issue by nmpribeiro** [BrainiumLLC/cargo-mobile#32]
Hi, when I try to run in my android simulator, I get the following:

`Unable to determine application id: com.android.tools.idea.run.ApkProvisionException: The currently selected variant "arm64-debug" uses split APKs, but none of the 1 split apks are compatible with the current device with ABIs "x86, armeabi-v7a, armeabi".
`

Do you have any idea about this?

**Comment by francesca64** [comment]
Thanks for asking! In Android Studio, there are Build Variants for each supported architecture and profile pair:
<img width="1248" alt="build-variants" src="https://user-images.githubusercontent.com/2096580/127205814-af000db3-ada5-476d-82b4-9516b1aa52a3.png">
You can also get to it through View -> Tool Windows -> Build Variants.

**Comment by nmpribeiro** [comment]
Thank you very much @francesca64 ! It works very well like that :)
