### ISSUE TITLE
Does not list connected android devices

### ISSUE THREAD

**Issue by katyo** [BrainiumLLC/cargo-mobile#69]
I have android phone connected via network. I can list it using adb and so install and run apks. `cargo-apk` also works perfect. But `cargo-mobile` failed to list it.

```
$ adb connect 192.168.100.66
connected to 192.168.100.66:5555

$ adb devices
List of devices attached
192.168.100.66:5555	device


$ cargo mobile android list -v
[2022-02-22T18:16:12Z INFO  bossy] running command "adb devices" and waiting for output
  -- none --

$ cargo mobile --version
cargo-mobile v0.1.0
Contains commits up to "iOS build scripts (#66)"
```

**Comment by Zeerooth** [comment]
Hello!
I've found the problem in the code
https://github.com/BrainiumLLC/cargo-mobile/blob/08aae511de659fdb581255fa77fa913a22cf8ba8/src/android/adb/device_list.rs#L43
IP addresses do not match the regex here, I'll try to provide the PR with a solution soon
