### ISSUE TITLE
Why is `gen/` gitignored and how should we edit the files within

### ISSUE THREAD

**Issue by Cactice** [BrainiumLLC/cargo-mobile#75]
The name `gen/` suggests it's short for generated.
Usually generated files shouldn't be edited so my expectation is that there is a way to customize the files within `gen/` without editing them directly.
However, I am not sure how to customize the files within `gen/` without editing the files themselves.

So for example, if I want to edit gen/apple/project.yml, then what is the recommended way to edit?

**Comment by ArthurKValladares** [comment]
` gen/apple/project.yml` gets generated from the template in [`templates/platforms/xcode/project.yml.hbs`](https://github.com/BrainiumLLC/cargo-mobile/blob/master/templates/platforms/xcode/project.yml.hbs). To edit the content there, you would add the corresponding sections to your app's `Cargo.toml` metadata sections, like this:

```
[package.metadata.cargo-apple.ios]
additional-targets = [...]
asset-catalogs = [...]
frameworks = [...]
post-build-scripts = [...]
command-line-arguments = [...]
```

The supported metadata can be found in the [`Platform` struct in `apple/config/mod.rs` ](https://github.com/BrainiumLLC/cargo-mobile/blob/20f2d1aee8b9c94de32fff40d9b0b6c15147966b/src/apple/config/mod.rs#L55-L67) Some configuration info can also be found in [`Config`](https://github.com/BrainiumLLC/cargo-mobile/blob/20f2d1aee8b9c94de32fff40d9b0b6c15147966b/src/apple/config/mod.rs#L290-L301).

**Comment by Cactice** [comment]
I see, that answers my question.
Thank you for the quick response.

It might be worth documenting somewhere👍
